### ISSUE TITLE
Additional Angular features

### ISSUE THREAD

**Issue by rdhelms** [jjlangholtz/angular_rails_template#2]
In order to use angular-ui-router and angular-local-storage, I had to additionally add those to the package.json dependencies, add them as requirements in application.js, and rewrite the base app.js file to use an angular.config() method instead of defining the controller directly.

See here (unfinished project, but has modifications to template): https://github.com/rdhelms/multiboard 

Overall very helpful template, though! Saved a ton of time.

**Comment by rdhelms** [comment]
Oh also - if you add the angular-rails-templates gem, then you can access the templateUri file paths really easily.

**Comment by jjlangholtz** [comment]
Thanks for the feedback @rdhelms. I just spent time looking through `angular-rails-templates` and `angular-ui-route` and they seem like great out of the box additions that you would almost always want. `angular-local-storage` I'm not so sure about as it seems a little more situational.

I'll go ahead and put together a PR that includes those additions!
